### ISSUE TITLE
missing dependencies in package.json

### ISSUE THREAD

**Issue by nxmohamad** [simalexan/api-lambda-save-dynamodb#1]
correct me if I'm wrong but isn't the package.json supposed to contain aws-sdk and uuid? since they are used in index.js

**Comment by simalexan** [comment]
Hi @nxmohamad!

They are already provided within the AWS Lambda environment. `aws-sdk` is provided out-of-the-box and `uuid` is the dependency of `aws-sdk`, so there is no need to add these dependencies to the component `package.json`. 

Hope this helps!

**Comment by nxmohamad** [comment]
Oh! Thank you.

**Comment by simalexan** [comment]
@nxmohamad you’re welcome!
