### ISSUE TITLE
Help request - {"message":"Missing Authentication Token"}

### ISSUE THREAD

**Issue by i001962** [simalexan/api-lambda-save-dynamodb#4]
After the 1 click deploy from the serverless repo I get stuck.
I'm trying to use this but not sure what to put into the url or curl command to to make the API call.

When I call https://${SaveApi}.execute-api.${AWS::Region}.amazonaws.com/prod/save I get an unauthorized error. What query parameters should be used? Does something need to get passed in the header like an API key? Also, any hint at what a curl command may look like would be appreciated. 

I will create an updated readme.md make a pull request once I get this is sorted. Thank you.

**Comment by cuckoointernet** [comment]
Are you sure you are submitting exactly as: https://github.com/simalexan/api-lambda-save-dynamodb/blob/master/template.yml#L66 check the URL for typo's because the only way to receive that error is if you aren't posting to the right URL.

**Comment by simalexan** [comment]
@cuckoointernet thanks for jumping in!

@i001962 please let me know how are you calling this service?
a standard HTTP `GET` Request would be fine

`curl --location --request POST 'https://YOUR-API-ID.execute-api.us-east-1.amazonaws.com/prod/save' \
--data-raw '{
  "someData": "someValue"
}'`

**Comment by i001962** [comment]
Thanks for the info. I’ll get back to this in two weekends. I was able to get unblocked using postman to make the call.

**Comment by simalexan** [comment]
@i001962 Thanks, I will also take some time to redefine this service, as it can be even more efficient and cost-effective. (Even more time saving)

Sorry again for the delay
